language: java

dist: xenial

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "KTPnQ8pHPefLXT4qGsNMPERZ8KmgDoZcHR+xDe/OYjIXE9zX42gBEtCh2Zmj6v2v9wdqTMbi9arrXBpPnE3M6IyVXwgHwR6dg/ZMqT8+jYp1Pbavh+r2Y008cOXuowDfbCdK75GXMtbqc88oLjsdwZMJedHq3YITc/AlSZJ5ag5C+17RRRJ3xJFbxOxx7G4L5IwT1Xhgf+6oDH1hf0Jc1y19keos63ZdUETFISlAP0EFZM4pmrqneDixH9cIPsjTa8+NKD3FtUHTUFC+Ve/VoHaf8GZ8nNm9xZahxsbckvlAjTGKbH7YD1bP/QXRRT+6E6qvx0C+vHL+J0nu07bMz8QImD+rPGFBScGCWYi9cCpLw0YU6is/67yA0KCtPHfCCqiOzK9whdNQN2G3vKYbU3/E19zzmWVzu5M4m11h1LzHY21yfu0AWxsv/M2OcFDKXmtfjugvVW5TohSvH7KkN2YcHI718xzgLkT3eOwWeG8KLZ/1Sg7qw5Z0wa0v/pPam/2geep99Tbq3cSZK+w0tQMmlII//zIXo4npwnXx+y1WbL7QsD0rwrlZ6C5hZ33pdLhfzHygSH+2IyGCBfEr2zCa2FTdjnBj5S/PrcpWXlIaSktiA03EDp+5H1od5+Mr41o9GJKwGs6lgcMWQtgnmgEePDYhh8yknkUEDdLdZIU="
    - secure: "UQV4cYCoykoWn/ywbFrG16SUAstecIIvTFmPtVMkUhiwCgnKzK9v3EbtTA14GD7Q9uJOZB1roMfM6D3HQAMZThslElE/yvDoNND9+6BYNImFVOb1aEcN/E0eGuGQVrrCZuJji4MIuKb7RSrtNN8y5ZNGPRq3XPpOmPodC66xYxWkZF8HPDIY/QpGZbW3cOrDlKyht5bqYa3DEuJx9H0m6+MrZx7x7fBekrz7nDRG8FCqAm731UkSacccx4Ds4SKXnouuOVHR2cQX9LulIB+3HSzLIKxivKVD+t5HZhOMzKFIw3b05s8xhwfjjR1rK3qkUffHA4hj105HGVHdFI5YVUJ1Zakni+zuV+1yU28JN+MqxgmxFdzggoh9pqa2sPnH5agCT+PPWB3HMKZAPesA5mzA+R14FV5JIuVicJeS3R/xQi/cHzOHtYcAJLM0/Qgo1EiWBfUqwtySjS1MChp5QhfMa3XTWlrbkRNf8ubhlpoyPPHPxGl0qnutAek7YwoWlc6gycWz7Mb6hgAMTGbt5V2szH6PkRQ/zdzgWE/t3GshOmKGpsPdhx/YGZU377Wve48cApw7Z7fl0ZaOwMV4q6PsjaYx88abZt+0vlwCtw5ugmxYl9mFztnkasv4BlnwiVmyhbvFOtDuA9wGW1FXGy8reN+uK/GJfOhoNHuHTxU="
    - secure: "LHWJ/2J77CYs/qclP+UaFTBnz+Hp5k7mqi7CTlP0avUviLsO5Nh5IegkzD/X3I/CrRhzQsRJhaqGEoLFWIqtz5m7NeeB7LV7oRatZ+eucyZbY1TyuL+1eK6Wp0oUfvGuTLf4p9YjJYm6fgVQNRysDPzh7iALUrcKN4IqzHmHO10zbWF3mgjT2bJoS8UvB3GNiJBHPuxb4+0Cd2hHVel8+R/A2Ai7LS2rk0vJS5QIG9j2E51ueCu69pEx9vBvgtHW5RKXiB4U8gUkCRzvdXoRDmtsypHyzAlYW8xlUqAMErbOdBEZb1f/HFJjXhwnFIP1pJ5WYVuFLOLz/cHGGM4zT70+6KJzUpy0dxUfedulWbPjTUNm9ItKIrbLxGyLiTn+02Sd21y3qNDjggDh4Eqi+Lgw2Adj5FSVK1Y1IMojUoo4ortoggQWxc+w4sgtv+5mv5lZtFpD1HKHzu4x6g4nmadGZCx1ftmXhu+OScw91/QVL6ASKiypAAZp2BfGGcJ4rvvRwVkOm7FYiqis2uMSB+li3rnUBYCHyx3yexPXwGuntQT+i322ozo9DKcDQSNe8cdZezgJjekbmv0V4KcGezEab5N8+RTo9sH9Y2I+t4wYE3W1NpBnWT9oVORTeKiOzG331qJQZjcZXKETUlgg10/pY2JU4FXI/6+knFB2K+o="
  
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin  

jdk: oraclejdk11
      
services:
  - docker

script: 
  -   cd impc_prod_tracker
  -   mvn clean package


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        cd $TRAVIS_BUILD_DIR;
        docker-compose build;
        docker tag impc-production-tracker_prod_tracker:latest "$DOCKER_USERNAME"/"$DOCKER_REPO":$(git rev-parse --short HEAD);
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "$DOCKER_USERNAME"/"$DOCKER_REPO":$(git rev-parse --short HEAD);
        docker logout;
    fi
