apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-service
  name: api-service
  namespace: mi-production-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-service
    spec:
      imagePullSecrets:
        - name: trackerapiregistrycredentials
      containers:
        - image: dockerhub.ebi.ac.uk/mouse-informatics/impc-production-tracker-mirror:latest
        imagePullPolicy: Always
        name: api-service
        envFrom:
        - configMapRef:
            name: database-conn
        env:
        - name: DOCKER_PRODUCTION
          value: "TRUE"
        - name: EBI_PROXY
          value: "TRUE"
        - name: AAP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: aap-domain
              key: domain
        - name: TRACKER_POSTGRESQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_password
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /tracker-api
        - name: REDEPLOY_KEY
          value: "STRING_REPLACED_DURING_REDEPLOY"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
