apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-service-sandbox
  name: api-service-sandbox
  namespace: mi-production-tracker-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-sandbox
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-service-sandbox
    spec:
      imagePullSecrets:
      - name: trackerapiregistrycredentials
      containers:
      - image: dockerhub.ebi.ac.uk/mouse-informatics/impc-production-tracker-mirror:latest
        imagePullPolicy: Always
        name: api-service-sandbox
        env:
        - name: EBI_PROXY
          value: "TRUE"
        - name: GENTAR_SCHEMA
          value: "TRUE"
        - name: AAP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: aap-domain
              key: domain
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /production-tracker-sandbox-api
        - name: TRACKER_POSTGRESQL_DB_HOST
          value: production-tracker-database
        - name: TRACKER_POSTGRESQL_DB_PORT
          value: "5432"
        - name: REDEPLOY_KEY
          value: "STRING_REPLACED_DURING_REDEPLOY"
        volumeMounts:
        - name: tz-gb
          mountPath: /etc/localtime
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      volumes:
      - name: tz-gb
        hostPath:
          path: /usr/share/zoneinfo/GB
